apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultation-service
  template:
    metadata:
      labels:
        app: consultation-service
    spec:
      containers:
      - name: consultation-service
        image: backend-consultation-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
        env:
        - name: PORT
          value: "5003"
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/mediconnect_consultation
        - name: SHARED_IDENTITY_MONGODB_URI
          value: mongodb://mongodb:27017/mediconnect_identity
        envFrom:
        - configMapRef:
            name: mediconnect-env
        - secretRef:
            name: mediconnect-secrets
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: consultation-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: consultation-service
spec:
  selector:
    app: consultation-service
  ports:
  - port: 5003
    targetPort: 5003